### ISSUE TITLE
Upgrade breaks instaloader

### ISSUE THREAD

**Issue by Fickbert** [instaloader/instaloader#293]
Currently I am on instaloader 4.2.2., when I upgrade to 4.2.5. via pip3 install --upgrade instaloader it says

> Installing collected packages: style, update, chardet, certifi, idna, urllib3, requests, instaloader
> Successfully installed certifi-2019.3.9 chardet-3.0.4 idna-2.8 instaloader-4.2.5 requests-2.21.0 style-1.1.0 update-0.0.1 urllib3-1.24.3

but when I try to use instaloader afeterwards no matter what it gives the following error traceback:

> $ instaloader
> Traceback (most recent call last):
>   File "/usr/local/bin/instaloader", line 7, in <module>
>     from instaloader.__main__ import main
>   File "/home/xxx/.local/lib/python3.5/site-packages/instaloader/__init__.py", line 16, in <module>
>     from .instaloader import Instaloader
>   File "/home/xxx/.local/lib/python3.5/site-packages/instaloader/instaloader.py", line 16, in <module>
>     from typing import Any, Callable, ContextManager, Iterator, List, Optional, Set, Union, cast
> ImportError: cannot import name 'ContextManager'

What is going wrong?

**Comment by aandergr** [comment]
Oh, this is due to a mistake we made with 4.2.5. To workaround, either

- downgrade Instaloader to 4.2.4, or
- upgrade Python to >= 3.6.

**Comment by Fickbert** [comment]
Is there a possibility to install 4.2.4 via pip3? I'm afraid upgrading Python to >= 3.6 will break other things I use Python for.

**Comment by aandergr** [comment]
> Is there a possibility to install 4.2.4 via pip3?

Yes, you can specify an exact version like this:
`pip3 install instaloader==4.2.4`

**Comment by aandergr** [comment]
This is fixed with version 4.2.6. Thanks for reporting!
